
SC_PACKAGE = 'SC_PACKAGE'
NEMO_PATH = 'NEMO_PATH'
CONDUIT_PATH = 'CONDUIT_PATH'
S_2_US = 10**6
MB_TO_B = 1024**2
CONDUIT_URL = 'http://iapp405.iil.intel.com:2232'
CONDUIT_POST_PROC = 'speedsim_post_processing'
CONDUIT_HW = 'speedsim_hw'
SPEEDSIM_DEBUG = 'SPEEDSIM_DEBUG'
