# Generated by Django 3.0.3 on 2020-06-11 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dlmodeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='run_complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='run_issue_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 13, 48, 56, 746102, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='summary',
            name='status',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='summary',
            name='overlap_report',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='summary',
            name='param_report',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='summary',
            name='param_scaleout_config',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
