# Generated by Django 3.0.3 on 2020-06-12 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dlmodeling', '0002_auto_20200611_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='config_df',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='run_summary_df',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='run_issue_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 10, 46, 50, 30316, tzinfo=utc)),
        ),
    ]
